In [1]:
import numpy as np
import pandas as pd
from collections import OrderedDict
from time import time
import os, sys

#from prepare_data import get_sliding_window

In [2]:
sys.path.append('../larry/')

In [3]:
from prepare_data import get_sliding_window

In [4]:
# read in csv, change column names
etf = pd.read_csv('../data/tetfp.csv')
col_dtypes = OrderedDict(code=str, date=str, name=str, open=float, high=float, low=float, close=float, volume=int)

etf.columns=col_dtypes.keys()

etf.head()

code      date    name   open   high    low  close  volume
0    50  20130102  元大台灣50  54.00  54.65  53.90  54.40   16487
1    50  20130103  元大台灣50  54.90  55.05  54.65  54.85   29020
2    50  20130104  元大台灣50  54.85  54.85  54.40  54.50    9837
3    50  20130107  元大台灣50  54.55  54.55  53.90  54.25    8910
4    50  20130108  元大台灣50  54.00  54.20  53.65  53.90   12507

In [5]:
etf= etf[:1286] # select 台灣50 
etf.tail()

code      date    name   open   high    low  close  volume
1281    50  20180327  元大台灣50  83.00  83.40  82.95  83.40    3277
1282    50  20180328  元大台灣50  82.90  82.90  82.20  82.25    4161
1283    50  20180329  元大台灣50  82.25  82.35  81.80  82.10    4099
1284    50  20180330  元大台灣50  82.65  83.05  82.65  82.85    4994
1285    50  20180331  元大台灣50  82.85  83.05  82.75  82.95     878

In [6]:
etf['target'] = etf.close.diff().fillna(0)
etf['target_signal'] = np.where(etf.close.diff().fillna(0) >=0,1,-1) 
etf

code      date    name   open   high    low  close  volume  target  \
0       50  20130102  元大台灣50  54.00  54.65  53.90  54.40   16487    0.00   
1       50  20130103  元大台灣50  54.90  55.05  54.65  54.85   29020    0.45   
2       50  20130104  元大台灣50  54.85  54.85  54.40  54.50    9837   -0.35   
3       50  20130107  元大台灣50  54.55  54.55  53.90  54.25    8910   -0.25   
4       50  20130108  元大台灣50  54.00  54.20  53.65  53.90   12507   -0.35   
5       50  20130109  元大台灣50  53.75  54.30  53.75  54.10    7529    0.20   
6       50  20130110  元大台灣50  54.30  54.65  54.15  54.50   13953    0.40   
7       50  20130111  元大台灣50  54.70  54.80  54.35  54.45   11837   -0.05   
8       50  20130114  元大台灣50  54.00  54.50  53.80  54.50    7282    0.05   
9       50  20130115  元大台灣50  54.20  54.45  53.90  54.00    6609   -0.50   
10      50  20130116  元大台灣50  54.05  54.05  53.70  53.70    8142   -0.30   
11      50  20130117  元大台灣50  53.90  54.20  53.20  53.30   10084   -0.40   
12      50  20130118  元大台灣50  53.95  53.95  53.70  53.95    5410    0.65   
13      50  20130121  元大台灣50  53.95  54.05  53.55  53.90    4525   -0.05   
14      50  20130122  元大台灣50  54.30  54.30  53.70  54.05   10501    0.15   
15      50  20130123  元大台灣50  54.20  54.30  53.90  54.00    7266   -0.05   
16      50  20130124  元大台灣50  53.75  53.90  53.25  53.70   11334   -0.30   
17      50  20130125  元大台灣50  53.65  53.70  53.20  53.50    8521   -0.20   
18      50  20130128  元大台灣50  53.70  53.95  53.65  53.75    8708    0.25   
19      50  20130129  元大台灣50  53.95  54.50  53.95  54.50   21973    0.75   
20      50  20130130  元大台灣50  54.50  54.75  54.45  54.60   21672    0.10   
21      50  20130131  元大台灣50  54.50  54.60  54.30  54.60   12643    0.00   
22      50  20130201  元大台灣50  54.70  54.85  54.60  54.80   15057    0.20   
23      50  20130204  元大台灣50  54.85  55.40  54.85  55.20   30980    0.40   
24      50  20130205  元大台灣50  54.90  55.10  54.90  55.00   15988   -0.20   
25      50  20130206  元大台灣50  55.20  55.50  55.20  55.40   29434    0.40   
26      50  20130218  元大台灣50  55.50  55.90  55.45  55.60   29739    0.20   
27      50  20130219  元大台灣50  55.60  55.75  55.55  55.65   16817    0.05   
28      50  20130220  元大台灣50  55.90  56.20  55.90  56.10   21814    0.45   
29      50  20130221  元大台灣50  55.90  56.05  55.70  55.70    9951   -0.40   
...    ...       ...     ...    ...    ...    ...    ...     ...     ...   
1256    50  20180209  元大台灣50  78.60  79.20  78.00  79.05   16211   -1.55   
1257    50  20180212  元大台灣50  79.55  79.90  79.40  79.70    8443    0.65   
1258    50  20180221  元大台灣50  81.40  81.70  81.10  81.50   11646    1.80   
1259    50  20180222  元大台灣50  81.50  81.50  80.75  81.00    3749   -0.50   
1260    50  20180223  元大台灣50  81.40  82.10  81.40  82.00    3779    1.00   
1261    50  20180226  元大台灣50  82.55  82.80  82.35  82.40    3289    0.40   
1262    50  20180227  元大台灣50  83.10  83.20  82.35  82.35    7663   -0.05   
1263    50  20180301  元大台灣50  81.55  81.95  81.15  81.75    4344   -0.60   
1264    50  20180302  元大台灣50  80.85  81.20  80.45  81.15    6262   -0.60   
1265    50  20180305  元大台灣50  81.10  81.50  80.65  80.75    3723   -0.40   
1266    50  20180306  元大台灣50  81.65  82.15  81.60  82.15    5732    1.40   
1267    50  20180307  元大台灣50  81.75  82.45  81.70  81.80    2619   -0.35   
1268    50  20180308  元大台灣50  82.15  82.80  82.15  82.75    3232    0.95   
1269    50  20180309  元大台灣50  82.90  83.00  82.70  82.85    2832    0.10   
1270    50  20180312  元大台灣50  83.60  84.25  83.55  84.15    8752    1.30   
1271    50  20180313  元大台灣50  84.35  84.95  84.30  84.95    9837    0.80   
1272    50  20180314  元大台灣50  84.35  84.45  84.00  84.30    3415   -0.65   
1273    50  20180315  元大台灣50  84.00  84.30  83.90  84.25    3506   -0.05   
1274    50  20180316  元大台灣50  84.00  84.20  83.10  83.90    5510   -0.35   
1275    50  20180319  元大台灣50  83.65  84.10  83.45  83.85    2035   -0.05   
1276    50  20180320  元大台灣50  83.20  83.80  83.20  83.

In [7]:
 from sklearn import preprocessing

def normalize(df):
    newdf= df.copy()
    min_max_scaler = preprocessing.MinMaxScaler()

    newdf['open'] = min_max_scaler.fit_transform(df.open.values.reshape(-1,1))
    newdf['low'] = min_max_scaler.fit_transform(df.low.values.reshape(-1,1))
    newdf['high'] = min_max_scaler.fit_transform(df.high.values.reshape(-1,1))
    newdf['volume'] = min_max_scaler.fit_transform(df.volume.values.reshape(-1,1))
    newdf['close'] = min_max_scaler.fit_transform(df.close.values.reshape(-1,1))
    newdf['target'] = min_max_scaler.fit_transform(df.target.values.reshape(-1,1))
    newdf['target_signal'] = min_max_scaler.fit_transform(df.target_signal.values.reshape(-1,1))
    #newdf['target_signal'] = df.target_signal
    return newdf
new_etf = normalize(etf)

/root/miniconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
new_etf

code      date    name      open      high       low     close  \
0       50  20130102  元大台灣50  0.020144  0.032951  0.027182  0.039660   
1       50  20130103  元大台灣50  0.046043  0.044413  0.048641  0.052408   
2       50  20130104  元大台灣50  0.044604  0.038682  0.041488  0.042493   
3       50  20130107  元大台灣50  0.035971  0.030086  0.027182  0.035411   
4       50  20130108  元大台灣50  0.020144  0.020057  0.020029  0.025496   
5       50  20130109  元大台灣50  0.012950  0.022923  0.022890  0.031161   
6       50  20130110  元大台灣50  0.028777  0.032951  0.034335  0.042493   
7       50  20130111  元大台灣50  0.040288  0.037249  0.040057  0.041076   
8       50  20130114  元大台灣50  0.020144  0.028653  0.024320  0.042493   
9       50  20130115  元大台灣50  0.025899  0.027221  0.027182  0.028329   
10      50  20130116  元大台灣50  0.021583  0.015759  0.021459  0.019830   
11      50  20130117  元大台灣50  0.017266  0.020057  0.007153  0.008499   
12      50  20130118  元大台灣50  0.018705  0.012894  0.021459  0.026912   
13      50  20130121  元大台灣50  0.018705  0.015759  0.017167  0.025496   
14      50  20130122  元大台灣50  0.028777  0.022923  0.021459  0.029745   
15      50  20130123  元大台灣50  0.025899  0.022923  0.027182  0.028329   
16      50  20130124  元大台灣50  0.012950  0.011461  0.008584  0.019830   
17      50  20130125  元大台灣50  0.010072  0.005731  0.007153  0.014164   
18      50  20130128  元大台灣50  0.011511  0.012894  0.020029  0.021246   
19      50  20130129  元大台灣50  0.018705  0.028653  0.028612  0.042493   
20      50  20130130  元大台灣50  0.034532  0.035817  0.042918  0.045326   
21      50  20130131  元大台灣50  0.034532  0.031519  0.038627  0.045326   
22      50  20130201  元大台灣50  0.040288  0.038682  0.047210  0.050992   
23      50  20130204  元大台灣50  0.044604  0.054441  0.054363  0.062323   
24      50  20130205  元大台灣50  0.046043  0.045845  0.055794  0.056657   
25      50  20130206  元大台灣50  0.054676  0.057307  0.064378  0.067989   
26      50  20130218  元大台灣50  0.063309  0.068768  0.071531  0.073654   
27      50  20130219  元大台灣50  0.066187  0.064470  0.074392  0.075071   
28      50  20130220  元大台灣50  0.074820  0.077364  0.084406  0.087819   
29      50  20130221  元大台灣50  0.074820  0.073066  0.078684  0.076487   
...    ...       ...     ...       ...       ...       ...       ...   
1256    50  20180209  元大台灣50  0.728058  0.736390  0.716738  0.737960   
1257    50  20180212  元大台灣50  0.755396  0.756447  0.756795  0.756374   
1258    50  20180221  元大台灣50  0.808633  0.808023  0.805436  0.807365   
1259    50  20180222  元大台灣50  0.811511  0.802292  0.795422  0.793201   
1260    50  20180223  元大台灣50  0.808633  0.819484  0.814020  0.821530   
1261    50  20180226  元大台灣50  0.841727  0.839542  0.841202  0.832861   
1262    50  20180227  元大台灣50  0.857554  0.851003  0.841202  0.831445   
1263    50  20180301  元大台灣50  0.812950  0.815186  0.806867  0.814448   
1264    50  20180302  元大台灣50  0.792806  0.793696  0.786838  0.797450   
1265    50  20180305  元大台灣50  0.800000  0.802292  0.792561  0.786119   
1266    50  20180306  元大台灣50  0.815827  0.820917  0.819742  0.825779   
1267    50  20180307  元大台灣50  0.818705  0.829513  0.822604  0.815864   
1268    50  20180308  元大台灣50  0.830216  0.839542  0.835479  0.842776   
1269    50  20180309  元大台灣50  0.851799  0.845272  0.851216  0.845609   
1270    50  20180312  元大台灣50  0.871942  0.881089  0.875536  0.882436   
1271    50  20180313  元大台灣50  0.893525  0.901146  0.896996  0.905099   
1272    50  20180314  元大台灣50  0.893525  0.886819  0.888412  0.886686   
1273    50  20180315  元大台灣50  0.883453  0.882521  0.885551  0.885269   
1274    50  20180316  元大台灣50  0.883453  0.879656  0.862661  0.875354   
1275    50  20180319  元大台灣50  0.873381  0.876791  0.872675  0.873938   
1276    50  20180320  元大台灣50  0.860432  0.868195  0.865522  0.872521   
1277    50  20180321  元大台灣50  0.877698  0.876791  0.876967  0.873938   
1278    50  20180322  元大台灣50  0.883453  0.891117  0.872675  0.865439   
1279    50  20180323  元大台灣50  0.821583  0.8280

In [9]:
new_etf.columns

Index(['code', 'date', 'name', 'open', 'high', 'low', 'close', 'volume',
       'target', 'target_signal'],
      dtype='object')

In [10]:
feature_cols = ['open', 'high', 'low', 'close', 'volume']

In [11]:
def prepare_data(feature_df, feature_cols, target_df, input_days=20,output_days=5):
    
    
    '''
    feature_df: the compelet feature set 
    feature_cols : subset of features,   if needs to select subset from the complete features set
    
    
    '''
    reduce_feature_df = feature_df[feature_cols].iloc[:len(feature_df)-output_days] 
    print ('len_X',reduce_feature_df.shape)
    print (reduce_feature_df)
    
    target_y  = target_df.iloc[input_days:]
    
    print ('len_y',target_y.shape)
    print (target_y)
    
    data_X =get_sliding_window(reduce_feature_df, n_days=input_days)
    data_y = get_sliding_window(target_y, n_days=output_days)
    
    data_dict = {'training_X': data_X,
                'training_y': data_y}
    
    return data_dict
    

In [12]:
data = prepare_data(new_etf, feature_cols, new_etf[['target','target_signal']])

len_X (1281, 5)
          open      high       low     close    volume
0     0.020144  0.032951  0.027182  0.039660  0.259106
1     0.046043  0.044413  0.048641  0.052408  0.466236
2     0.044604  0.038682  0.041488  0.042493  0.149203
3     0.035971  0.030086  0.027182  0.035411  0.133883
4     0.020144  0.020057  0.020029  0.025496  0.193330
5     0.012950  0.022923  0.022890  0.031161  0.111060
6     0.028777  0.032951  0.034335  0.042493  0.217227
7     0.040288  0.037249  0.040057  0.041076  0.182257
8     0.020144  0.028653  0.024320  0.042493  0.106978
9     0.025899  0.027221  0.027182  0.028329  0.095855
10    0.021583  0.015759  0.021459  0.019830  0.121191
11    0.017266  0.020057  0.007153  0.008499  0.153286
12    0.018705  0.012894  0.021459  0.026912  0.076040
13    0.018705  0.015759  0.017167  0.025496  0.061413
14    0.028777  0.022923  0.021459  0.029745  0.160177
15    0.025899  0.022923  0.027182  0.028329  0.106713
16    0.012950  0.011461  0.008584  0.019830  0.1

In [13]:
data['training_X'].shape

(1262, 20, 5)

In [14]:
data['training_y']  

array([[[ 0.60902256,  1.        ],
        [ 0.59398496,  1.        ],
        [ 0.62406015,  1.        ],
        [ 0.65413534,  1.        ],
        [ 0.56390977,  0.        ]],

       [[ 0.59398496,  1.        ],
        [ 0.62406015,  1.        ],
        [ 0.65413534,  1.        ],
        [ 0.56390977,  0.        ],
        [ 0.65413534,  1.        ]],

       [[ 0.62406015,  1.        ],
        [ 0.65413534,  1.        ],
        [ 0.56390977,  0.        ],
        [ 0.65413534,  1.        ],
        [ 0.62406015,  1.        ]],

       ..., 
       [[ 0.37593985,  0.        ],
        [ 0.60902256,  1.        ],
        [ 0.77443609,  1.        ],
        [ 0.42105263,  0.        ],
        [ 0.57142857,  0.        ]],

       [[ 0.60902256,  1.        ],
        [ 0.77443609,  1.        ],
        [ 0.42105263,  0.        ],
        [ 0.57142857,  0.        ],
        [ 0.70676692,  1.        ]],

       [[ 0.77443609,  1.        ],
        [ 0.42105263,  0.        ],
     

In [15]:
 from sklearn.model_selection import train_test_split 

X = data['training_X']
Y = data['training_y'][:,:,1]  # only use target signal 
Y = Y[:,:,np.newaxis] # expand one more axis to align with NN outoput 
print (X.shape)
print (Y.shape)


#K_binary = keras.utils.to_categorical(K_label,2)
X_train, X_test, Y_train,Y_test = train_test_split (X,Y, test_size=0.2,shuffle=True)

#Y_train =  Y_train[:,:,np.newaxis]
#Y_test =  Y_test[:,:,np.newaxis]
#Y_train = np.array(Y_train)
print (X_train.shape)
print (Y_train.shape)
print (Y_train[:10])

(1262, 20, 5)
(1262, 5, 1)
(1009, 20, 5)
(1009, 5, 1)
[[[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]]]


In [16]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.recurrent import LSTM
import keras


from keras.optimizers import Adam,SGD

Using TensorFlow backend.


In [17]:
from keras.layers import Input, Embedding, LSTM, Dense
from keras.models import Model
from keras.optimizers import Adam 
from keras.losses import binary_crossentropy
from keras.layers import Dropout
from keras.utils import to_categorical
from keras.layers import Reshape

from keras.layers import Lambda

#def build_model(input_length, input_dim):
input_length, input_dim = 20,5

d = 0.2

main_input = Input(shape=(input_length,input_dim),  name='main_input')
lstm_1 = LSTM(64, return_sequences=True, name='lastm_1')(main_input)
lstm_1 = Dropout(d)(lstm_1)
lstm_2 = LSTM(128, return_sequences=True, name='lastm_2')(lstm_1)
lstm_2 = Dropout(d)(lstm_2)
#lstm_3 = LSTM(128, return_sequences=False, name='lastm_3')(main_input)


lstm_3 = LSTM(128, return_sequences=False, name='lastm_3')(lstm_2)
lstm_3 = Dropout(d)(lstm_3)
logit = Dense(128, activation='relu', name='logit')(lstm_3)
logit = Dropout(d)(logit)

logit = Dense(64, activation='relu', name='logit_2')(logit)
logit = Dropout(d)(logit)


output = Dense(5, activation='sigmoid', name='output')(logit)
output = Dropout(d)(output)

# Using Lambda function to get multiple output 
# Need reshape to allign with Shape of Train_Y

output_0 = Lambda(lambda x: x[:,0])(output)
output_0 = Reshape((-1,))(output_0) 
output_1 = Lambda(lambda x: x[:,1])(output)
output_1 = Reshape((-1,))(output_1)
output_2 = Lambda(lambda x: x[:,2])(output)
output_2 = Reshape((-1,))(output_2)
output_3 = Lambda(lambda x: x[:,3])(output)
output_3 = Reshape((-1,))(output_3)
output_4 = Lambda(lambda x: x[:,4])(output)
output_4 = Reshape((-1,))(output_4)


'''
output_0 = Dense(1, activation='sigmoid', name='output_0')(logit)
output_1 = Dense(1, activation='sigmoid', name='output_1')(logit)
output_2 = Dense(1, activation='sigmoid', name='output_2')(logit)
output_3 = Dense(1, activation='sigmoid', name='output_3')(logit)
output_4 = Dense(1, activation='sigmoid', name='output_4')(logit)
'''




#loss_type = 'mse'
loss_type = 'binary_crossentropy'
combine_loss = [loss_type]*5



#combine_loss = ['binary_crossentropy','binary_crossentropy','binary_crossentropy','binary_crossentropy','binary_crossentropy']

'''
def combine_loss(y_true, y_pred):
    print (y_true.shape)
    y_true = to_categorical(y_true)
    loss_list = [category_loss(y_true[i,:], y_pred[i,:]) for i in range(len(y_true))]
    losses = sum(loss_list)
    return losses
'''

#outputs = [output_0,output_1,output_2, output_3, output_4]

model = Model(inputs=main_input, outputs=[output_0,output_1,output_2, output_3, output_4])

adam_op = Adam(lr=0.001)

model.compile(optimizer=adam_op, loss=combine_loss, metrics=['accuracy'])





# return 
    
    
    






  
# 20天、5維
#model = build_model( 20, 5 )

print (model.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main_input (InputLayer)         (None, 20, 5)        0                                            
__________________________________________________________________________________________________
lastm_1 (LSTM)                  (None, 20, 64)       17920       main_input[0][0]                 
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 20, 64)       0           lastm_1[0][0]                    
__________________________________________________________________________________________________
lastm_2 (LSTM)                  (None, 20, 128)      98816       dropout_1[0][0]                  
__________________________________________________________________________________________________
dropout_2 

In [18]:
print (Y_train.shape)
#Y= [Y_train[:,0],Y_train[:,1],Y_train[:,2],Y_train[:,3],Y_train[:,4]]
#Y= [Y_train[:,0,np.newaxis],Y_train[:,1,np.newaxis],Y_train[:,2,np.newaxis],Y_train[:,3,np.newaxis],Y_train[:,4,np.newaxis]]


#Y= [Y_train[:,0].squeeze(),Y_train[:,1].squeeze(),Y_train[:,2].squeeze(),Y_train[:,3].squeeze(),Y_train[:,4].squeeze(),]
#print (Y[0].shape)

Y = [Y_train[:,i,:] for i in range(5)]  # simplify expression 

model.fit (X_train, Y, batch_size=64, epochs=50, validation_split=0.2,verbose=2)

(1009, 5, 1)
Train on 807 samples, validate on 202 samples
Epoch 1/50
 - 4s - loss: 12.4835 - reshape_1_loss: 2.6474 - reshape_2_loss: 2.1955 - reshape_3_loss: 2.4680 - reshape_4_loss: 2.4200 - reshape_5_loss: 2.7526 - reshape_1_acc: 0.5167 - reshape_2_acc: 0.5428 - reshape_3_acc: 0.5143 - reshape_4_acc: 0.5316 - reshape_5_acc: 0.5093 - val_loss: 3.4884 - val_reshape_1_loss: 0.6966 - val_reshape_2_loss: 0.7006 - val_reshape_3_loss: 0.6984 - val_reshape_4_loss: 0.6929 - val_reshape_5_loss: 0.6999 - val_reshape_1_acc: 0.4703 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.4455 - val_reshape_4_acc: 0.4950 - val_reshape_5_acc: 0.4554
Epoch 2/50
 - 2s - loss: 11.9832 - reshape_1_loss: 2.1297 - reshape_2_loss: 2.7858 - reshape_3_loss: 2.3224 - reshape_4_loss: 2.4769 - reshape_5_loss: 2.2684 - reshape_1_acc: 0.5452 - reshape_2_acc: 0.4994 - reshape_3_acc: 0.5390 - reshape_4_acc: 0.5415 - reshape_5_acc: 0.5514 - val_loss: 3.5076 - val_reshape_1_loss: 0.6993 - val_reshape_2_loss: 0.7099 - va

Epoch 15/50
 - 2s - loss: 11.5218 - reshape_1_loss: 2.2486 - reshape_2_loss: 2.1675 - reshape_3_loss: 2.3541 - reshape_4_loss: 2.3687 - reshape_5_loss: 2.3829 - reshape_1_acc: 0.5551 - reshape_2_acc: 0.5390 - reshape_3_acc: 0.5204 - reshape_4_acc: 0.5415 - reshape_5_acc: 0.5440 - val_loss: 3.5187 - val_reshape_1_loss: 0.6988 - val_reshape_2_loss: 0.7093 - val_reshape_3_loss: 0.7114 - val_reshape_4_loss: 0.6952 - val_reshape_5_loss: 0.7039 - val_reshape_1_acc: 0.4703 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.4455 - val_reshape_4_acc: 0.4950 - val_reshape_5_acc: 0.4554
Epoch 16/50
 - 2s - loss: 12.1751 - reshape_1_loss: 2.4148 - reshape_2_loss: 2.5751 - reshape_3_loss: 2.3489 - reshape_4_loss: 2.2823 - reshape_5_loss: 2.5541 - reshape_1_acc: 0.5539 - reshape_2_acc: 0.5316 - reshape_3_acc: 0.5031 - reshape_4_acc: 0.5551 - reshape_5_acc: 0.5341 - val_loss: 3.5235 - val_reshape_1_loss: 0.6996 - val_reshape_2_loss: 0.7077 - val_reshape_3_loss: 0.7146 - val_reshape_4_loss: 0.6954 - v

Epoch 30/50
 - 2s - loss: 12.4671 - reshape_1_loss: 2.3311 - reshape_2_loss: 2.4648 - reshape_3_loss: 2.6889 - reshape_4_loss: 2.4692 - reshape_5_loss: 2.5131 - reshape_1_acc: 0.5428 - reshape_2_acc: 0.5316 - reshape_3_acc: 0.5118 - reshape_4_acc: 0.5477 - reshape_5_acc: 0.5403 - val_loss: 3.5151 - val_reshape_1_loss: 0.6984 - val_reshape_2_loss: 0.7053 - val_reshape_3_loss: 0.7114 - val_reshape_4_loss: 0.6950 - val_reshape_5_loss: 0.7049 - val_reshape_1_acc: 0.4703 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.4455 - val_reshape_4_acc: 0.4950 - val_reshape_5_acc: 0.4554
Epoch 31/50
 - 2s - loss: 11.9490 - reshape_1_loss: 2.4810 - reshape_2_loss: 2.3016 - reshape_3_loss: 2.2185 - reshape_4_loss: 2.4794 - reshape_5_loss: 2.4684 - reshape_1_acc: 0.5378 - reshape_2_acc: 0.5527 - reshape_3_acc: 0.5229 - reshape_4_acc: 0.5378 - reshape_5_acc: 0.5514 - val_loss: 3.5216 - val_reshape_1_loss: 0.7018 - val_reshape_2_loss: 0.7058 - val_reshape_3_loss: 0.7145 - val_reshape_4_loss: 0.6973 - v

Epoch 45/50
 - 2s - loss: 11.8566 - reshape_1_loss: 2.3796 - reshape_2_loss: 2.3331 - reshape_3_loss: 2.5463 - reshape_4_loss: 2.3318 - reshape_5_loss: 2.2657 - reshape_1_acc: 0.5242 - reshape_2_acc: 0.5403 - reshape_3_acc: 0.5068 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5527 - val_loss: 3.5218 - val_reshape_1_loss: 0.7020 - val_reshape_2_loss: 0.7072 - val_reshape_3_loss: 0.7092 - val_reshape_4_loss: 0.6969 - val_reshape_5_loss: 0.7065 - val_reshape_1_acc: 0.4703 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.4455 - val_reshape_4_acc: 0.4752 - val_reshape_5_acc: 0.4554
Epoch 46/50
 - 1s - loss: 11.4522 - reshape_1_loss: 2.4077 - reshape_2_loss: 2.2895 - reshape_3_loss: 2.1100 - reshape_4_loss: 2.2656 - reshape_5_loss: 2.3794 - reshape_1_acc: 0.5366 - reshape_2_acc: 0.5440 - reshape_3_acc: 0.5403 - reshape_4_acc: 0.5502 - reshape_5_acc: 0.5465 - val_loss: 3.5104 - val_reshape_1_loss: 0.6987 - val_reshape_2_loss: 0.7033 - val_reshape_3_loss: 0.7109 - val_reshape_4_loss: 0.6979 - v

In [ ]:
Y_ = [Y_test[:,i,:] for i in range(5)]

model.evaluate(X_test,Y_)

In [ ]:
model.save('../model/LSTM_20_5_D_180506.save')

In [ ]:
from sklearn.model_selection import train_test_split 

#K_binary = keras.utils.to_categorical(K_label,2)
x = data['training_X']
y = data['training_y'][:,:,1]
y = y[:,:,np.newaxis]
print (x.shape)
print (y.shape)


x_train, x_test, y_train,y_test = train_test_split (x,y, test_size=0.2,shuffle=True)

#Y_train =  Y_train[:,:,np.newaxis]
#Y_test =  Y_test[:,:,np.newaxis]
#Y_train = np.array(Y_train)
print (X_train.shape)
print (Y_train.shape)
print (Y_train[:10])

In [ ]:
y_ = [y_test[:,i,:] for i in range (5)]
model.evaluate(x_test,y_)