In [1]:
import numpy as np
import pandas as pd


from prepare_data import *

In [2]:
test_list = {'A': [0.44,0.46,0.46,0.85,0.78,0.99,0.25],
             'B': [0.41,0.47,0.02,0.82,0.76, 1.12,0.76],
            'C': [0.44,0.46,0.46,0.85,0.78,0.99,0.25],
            'D': [0.41,0.47,0.02,0.82,0.76, 1.12,0.76]}
test_df =pd.DataFrame(test_list)
print (test_df)

      A     B     C     D
0  0.44  0.41  0.44  0.41
1  0.46  0.47  0.46  0.47
2  0.46  0.02  0.46  0.02
3  0.85  0.82  0.85  0.82
4  0.78  0.76  0.78  0.76
5  0.99  1.12  0.99  1.12
6  0.25  0.76  0.25  0.76


In [3]:
print (get_sliding_window(test_df, 3))

a.strides (8, 56)
a.strides (8, 56)


s0 8 s1 56


length 7 features 4


[[[ 0.44  0.41  0.44  0.41]
  [ 0.46  0.47  0.46  0.47]
  [ 0.46  0.02  0.46  0.02]]

 [[ 0.46  0.47  0.46  0.47]
  [ 0.46  0.02  0.46  0.02]
  [ 0.85  0.82  0.85  0.82]]

 [[ 0.46  0.02  0.46  0.02]
  [ 0.85  0.82  0.85  0.82]
  [ 0.78  0.76  0.78  0.76]]

 [[ 0.85  0.82  0.85  0.82]
  [ 0.78  0.76  0.78  0.76]
  [ 0.99  1.12  0.99  1.12]]

 [[ 0.78  0.76  0.78  0.76]
  [ 0.99  1.12  0.99  1.12]
  [ 0.25  0.76  0.25  0.76]]]
